# Generated by Django 5.1.4 on 2025-03-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(max_length=50)),
                ('disaster_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('aid_received', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DisasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_id', models.CharField(max_length=50)),
                ('disaster_type', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('impact_level', models.CharField(max_length=50)),
                ('people_affected', models.IntegerField()),
                ('casualties', models.IntegerField()),
                ('infrastructure_damage_usd', models.FloatField()),
                ('relief_resources', models.CharField(max_length=255)),
                ('response_time_hours', models.IntegerField()),
                ('funds_allocated_usd', models.FloatField()),
                ('recovery_time_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('disaster_type', models.CharField(max_length=255)),
                ('impact_level', models.CharField(max_length=50)),
                ('cluster_label', models.CharField(max_length=50)),
                ('resource_name', models.CharField(max_length=255)),
                ('allocated_resources', models.FloatField()),
                ('source', models.CharField(default='default_source', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=50)),
                ('disaster_id', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost_usd', models.FloatField()),
                ('deployment_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('people_affected', models.IntegerField()),
                ('infrastructure_damage', models.FloatField()),
                ('funds_allocated', models.FloatField()),
                ('casualties', models.IntegerField()),
                ('resource_name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='DisasterCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('cluster_label', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('disaster_data', 'DisasterData'), ('userinput', 'UserInput')], max_length=20)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disasterdata')),
            ],
        ),
    ]
