# Generated by Django 5.1.4 on 2025-03-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedallocation',
            name='source',
        ),
    ]
