# Generated by Django 5.1.4 on 2025-03-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_optimizedallocation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDisasterCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('cluster_label', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('userinput', 'UserInput')], default='userinput', max_length=20)),
                ('user_disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinput')),
            ],
        ),
    ]
