# Generated by Django 5.1.4 on 2025-03-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdisastercluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedallocation',
            name='impact_level',
        ),
    ]
