# Generated by Django 5.1.4 on 2025-03-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedata',
            name='allocated_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
