"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os #new
import sys #new
import dj_database_url #new

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR)) #new 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c1rjj^(yz)kg%ayd8%3fxue_nzuc3kh(ya8ins=g1im+34_c--'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

DEBUG = os.getenv("DEBUG", "True") == "True" #new

# ALLOWED_HOSTS = [] #'drras.onrender.com', 'localhost', '127.0.0.1'

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,drras.onrender.com"
).split(",") #new

# ✅ Static files (for Render)
#STATIC_URL = '/static/'
#STATIC_ROOT = BASE_DIR / 'staticfiles'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

# ✅ CORS SETTINGS (Place outside INSTALLED_APPS)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Allow frontend to access the backend
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # Prevent CSRF issues when making API requests
]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies & authentication

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ✅ This should be above CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'DB1',
#         'USER': 'DRRAS',
#         'PASSWORD': 'pgdivakar',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

# import os
# import dj_database_url

# Detect if running on Render
IS_RENDER = "RENDER" in os.environ

if IS_RENDER:
    # ✅ Use Render's environment variable (DATABASE_URL)
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
else:
    # ✅ Use your local PostgreSQL database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'DB1',
            'USER': 'DRRAS',
            'PASSWORD': 'pgdivakar',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow requests from React app
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React app URL
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # ✅ Add this line
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
         'rest_framework.parsers.MultiPartParser',
    ],
}

















# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 MB limit

#import dj_database_url

#DATABASES = {
#    'default': dj_database_url.config(default='postgresql://drras_db_user:3zBo0LTzS9uYNohAtUMDKqXnfhtjkPK0@dpg-d42a9b63jp1c73afm8i0-a/drras_db')
#}
